version: "3"

volumes:
  mongo_data: {}
  mongo_backup: {}
  node_logs: {}

services:
  node:
    restart: always
    build:
      context: ./backend
      dockerfile: ../compose/node/Dockerfile
    # command: bash
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb://mongo:27017/<%=project_slug%>"
    volumes:
      - /home/app/<%=project_slug%>/node_modules
      - node_logs:/home/app/<%=project_slug%>/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    # tty: true
  mongo:
    restart: always
    image: mongo:3.6
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
#    ports:
#      - '27017:27017'
