version: "3"

volumes:
  mongo_data: {}
  mongo_backup: {}
  node_logs: {}
  node_modules:

networks:
  app-network:
    driver: bridge

services:
  node:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash
    environment:
      NODE_ENV: production
      DATABASE_URL: "mongodb://mongo:27017/<%=project_slug%>"
    volumes:
      - node_modules:/home/app/<%=project_slug%>/node_modules
      - node_logs:/home/app/<%=project_slug%>/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    networks:
      - app-network
    # tty: true
  mongo:
    restart: always
    image: mongo:4.2
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
#    ports:
#      - '27017:27017'
    networks:
      - app-network

