version: "3"

volumes:
  mongo_data: {}
  frontend: {}

services:
  node:
    # restart: always
    build:
      context: ./backend
      dockerfile: ../compose/node/Dockerfile_dev
    # command: nodemon --inspect=0.0.0.0:9229 --nolazy app.js
    ports:
      - "3000:3000"
      - "9229:9229"
    env_file:
      - .env
    volumes:
      - ./backend:/home/app/<%=project_slug%>
      - /home/app/<%=project_slug%>/node_modules
      - frontend:/home/app/<%=project_slug%>/src/client/build
    depends_on:
      - mongo

  client:
    build:
      context: ./frontend
      dockerfile: ../compose/client/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    volumes:
      - ./frontend:/home/app/client
      - /home/app/client/node_modules
      - frontend:/home/app/client/build

  mongo:
    image: mongo:3.6
    env_file:
      - .env
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
