version: '3'

volumes:
  mongo_data: {}


services:
  node:
    # restart: always
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile_dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/home/app/dating
      - /home/app/dating/node_modules
    depends_on:
      - mongo
  client:
    build:
      context: ./client
      dockerfile: ../compose/client/Dockerfile
    ports:
      - '3001:3000'
    env_file:
      - .env
    volumes:
      - ./client:/home/app/client
      - /home/app/client/node_modules

  mongo:
    image: mongo:3.4
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
    ports:
      - '127.0.0.1:27017:27017'
