version: "3"

volumes:
  mongo_data: {}
  mongo_backup: {}
  node_logs: {}

services:
  node:
    restart: always
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile
    # command: bash
    env_file:
      - .env
    volumes:
      - /home/app/{{cookiecutter.project_slug}}/node_modules
      - node_logs:/home/app/{{cookiecutter.project_slug}}/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    # tty: true
  mongo:
    restart: always
    image: mongo:3.6
    env_file:
    - .env
    command: mongod --storageEngine wiredTiger
    volumes:
      - mongo_data:/data/db
      - mongo_backup:/data/backup
#    ports:
#      - '27017:27017'
  nginx:
    restart: always
    build: ./compose/nginx
    depends_on:
      - node
    ports:
      - "80:80"
      - "443:443"
