version: '3'

volumes:
  mongo_data: {}


services:
  node:
    # restart: always
    build:
      context: .
      dockerfile: ./compose/node/Dockerfile_dev
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "mongodb://mongo:27017/improve-boilerplate"
      FACEBOOK_CLIENT_ID: 'your-client-id'
      FACEBOOK_CLIENT_SECRET: 'your-client-secret'
      GOOGLE_CLIENT_ID: 'your-client-id'
      GOOGLE_CLIENT_SECRET: 'your-client-secret'
    volumes:
      - .:/home/app/improve-boilerplate
      - /home/app/improve-boilerplate/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4
    command: mongod --smallfiles
    volumes:
      - mongo_data:/data/db
    ports:
      - '127.0.0.1:27017:27017'
