sudo: required

language: node_js

services:
  - docker

node_js:
  - "10.16.0"

env:
  - TOX_ENV=py36

before_install:
  - docker-compose -v
  - docker -v

script:
  # - sh tests/test_docker.sh
  - npm run test

install:
  - npm install -g yo
  - npm install
  - npm link

notifications:
  email:
    on_success: change
    on_failure: always
