sudo: required

services:
  - docker

language: node_js

node_js:
  - "10.16.0"

env:
  - TOX_ENV=py36

before_install:
  - docker-compose -v
  - docker -v

# script:
#   - sh tests/test_docker.sh

install:
  - npm install -g yo
  - npm install
  - npm run test

notifications:
  email:
    on_success: change
    on_failure: always
