sudo: required

language: python

services:
  - docker

before_install:
  - docker-compose -v
  - docker -v

script:
  - sh tests/test_docker.sh

notifications:
  email:
    on_success: change
    on_failure: always